---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-svc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: docker.io/ellenkorbes/gc19:service1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-svc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: docker.io/ellenkorbes/gc19:service2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dep-svc1
spec:
  # When using minikube, set the type to "NodePort"
  # When using Digital Ocean, set it to "LoadBalancer"
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
    name: http
  selector:
    app: service1
---
apiVersion: v1
kind: Service
metadata:
  name: dep-svc2
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
    protocol: TCP
    name: http
  selector:
    app: service2